dist: trusty
sudo: required
language: go

go:
  - 1.8.x
  - 1.9.x
  - master

go_import_path: github.com/Percona-Lab/clickhouse_exporter

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

  - make init

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
