dist: trusty
sudo: required
language: go

go:
  - 1.8.x
  - master

before_script:
  - PACKAGES=`go list ./... | grep -v vendor`
  - go get github.com/prometheus/promu
  - go get github.com/AlekSi/gocoverutil

script:
  - promu build
#  - gocoverutil test -v $PACKAGES

after_success:
#  - bash <(curl -s https://codecov.io/bash) -X fix