dist: bionic
language: go

services:
  - docker

go:
  - 1.13.x
  - master

go_import_path: github.com/Percona-Lab/clickhouse_exporter

matrix:
  fast_finish: true
  allow_failures:
    - go: master

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

  - make init

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
