{
 "title": "Clickhouse-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "machine", "label": "machine", "query": { "query": "label_values(instance)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(user)" } },
   { "name": "db_name", "label": "db_name", "query": { "query": "label_values(database)" } },
   { "name": "tablename", "label": "tablename", "query": { "query": "label_values(table)" } },
   {
    "name": "min_interval",
    "label": "min_interval",
    "query": "2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "sitename" }
  ]
 },
 "panels": [
  {
   "title": "System Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU MHz ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"clickhouse_cpu_frequency_m_hz_.*\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "clickhouse_memory_tracking", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "clickhouse_load_average1{instance=~\"$machine\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "clickhouse_table_parts_rows{instance=~\"$machine\", database=~\"$db_name\", table=~\"$tablename\", database!=\"system\"}",
       "legendFormat": "{{instance}} {{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Table Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "clickhouse_table_parts_bytes{instance=~\"$machine\", database=~\"$db_name\", table=~\"$tablename\", database!=\"system\"}",
       "legendFormat": "{{instance}} {{database}}.{{table}}"
      }
     ]
    },
    {
     "title": "Table Parts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "clickhouse_table_parts_count{instance=~\"$machine\", database=~\"$db_name\", table=~\"$tablename\", database!=\"system\"}",
       "legendFormat": "{{instance}} {{database}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking/Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Transfer Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(clickhouse_interface_http_receive_bytes_total[${min_interval}])",
       "legendFormat": "received {{instance}}"
      },
      {
       "expr": "increase(clickhouse_interface_http_send_bytes_total[${min_interval}])",
       "legendFormat": "send  {{instance}}"
      }
     ]
    },
    {
     "title": "Network Transfer Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(clickhouse_network_receive_bytes_eth0[${min_interval}])",
       "legendFormat": "receive {{instance}}"
      },
      {
       "expr": "increase(clickhouse_network_send_bytes_eth0[${min_interval}])",
       "legendFormat": "send {{instance}}"
      }
     ]
    },
    {
     "title": "Packet Loss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(clickhouse_network_receive_drop_eth0[${min_interval}])",
       "legendFormat": "received {{instance}}"
      },
      {
       "expr": "increase(clickhouse_network_send_drop_eth0[${min_interval}])",
       "legendFormat": "send  {{instance}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(clickhouse_http_connection[${min_interval}])",
       "legendFormat": "http conn {{instance}}"
      },
      {
       "expr": "increase(clickhouse_http_threads[${min_interval}])",
       "legendFormat": "http threads  {{instance}}"
      },
      {
       "expr": "increase(clickhouse_tcp_connection[$__rate_interval])",
       "legendFormat": "tcp conn {{instance}}"
      },
      {
       "expr": "increase(clickhouse_tcp_threads[$__rate_interval])",
       "legendFormat": "tcp threads {{instance}}"
      }
     ]
    },
    {
     "title": "Native Transfer Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(clickhouse_interface_native_receive_bytes_total[${min_interval}])",
       "legendFormat": "receive {{instance}}"
      },
      {
       "expr": "increase(clickhouse_interface_native_send_bytes_total[${min_interval}])",
       "legendFormat": "send {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Machine Query Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (instance) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryFinish\"\n        }[${min_interval}]\n    )\n) ",
       "legendFormat": "Success {{instance}}"
      },
      {
       "expr": "sum by (instance) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryStart\"\n        }[${min_interval}]\n    )\n) \n-\nsum by (instance) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryFinish\"\n        }[${min_interval}]\n    )\n) ",
       "legendFormat": "exception {{instance}}"
      }
     ]
    },
    {
     "title": "User Query Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "expr": "sum by (user) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryFinish\"\n        }[${min_interval}]\n    )\n) ",
       "legendFormat": "Success {{user}} "
      },
      {
       "expr": "sum by (user) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryStart\"\n        }[${min_interval}]\n    )\n) \n-\nsum by (user) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryFinish\"\n        }[${min_interval}]\n    )\n) ",
       "legendFormat": "exception {{user}}"
      }
     ]
    },
    {
     "title": "Table Query Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "expr": "sum by (table) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryFinish\"\n        }[${min_interval}]\n    )\n) ",
       "legendFormat": "Success {{table}} "
      },
      {
       "expr": "sum by (table) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryStart\"\n        }[${min_interval}]\n    )\n) \n-\nsum by (table) (\n    rate(\n        clickhouse_user_query_num{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\",\n            type=\"QueryFinish\"\n        }[${min_interval}]\n    )\n) ",
       "legendFormat": "exception {{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage Machine/User/Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum Memory Usage Per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (user) (\n    rate(\n        clickhouse_user_memory_usage{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Memory Usage Per Table",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (table) (\n    rate(\n        clickhouse_user_memory_usage{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "{{instance}} {{table}}"
      }
     ]
    },
    {
     "title": "Sum Memory Usage Per Machine",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\n    rate(\n        clickhouse_user_memory_usage{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Thread Usage Per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user) (\n    rate(\n        clickhouse_user_peak_thread_usage{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Thread Usage Per Table",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (table) (\n    rate(\n        clickhouse_user_peak_thread_usage{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Thread Usage Per Machine",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (\n    rate(\n        clickhouse_user_peak_thread_usage{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Read/Write/Result",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum Machine Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "read: {{instance}}"
      },
      {
       "expr": "sum by (instance) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "write: {{instance}}"
      },
      {
       "expr": "sum by (instance) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "result: {{instance}}"
      }
     ]
    },
    {
     "title": "Sum User Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (user) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "read: {{user}}"
      },
      {
       "expr": "sum by (user) (\n  rate(\n    clickhouse_user_written_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "write: {{user}}"
      },
      {
       "expr": "sum by (user) (\n  rate(\n    clickhouse_user_result_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "result: {{user}}"
      }
     ]
    },
    {
     "title": "Sum Table Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (table) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "read: {{table}}"
      },
      {
       "expr": "sum by (table) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "write: {{table}}"
      },
      {
       "expr": "sum by (table) (\n  rate(\n    clickhouse_user_read_bytes{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "result: {{table}}"
      }
     ]
    },
    {
     "title": "Sum Machine Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (\n  rate(\n    clickhouse_user_read_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "read: {{instance}}"
      },
      {
       "expr": "sum by (instance) (\n  rate(\n    clickhouse_user_written_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "write: {{instance}}"
      },
      {
       "expr": "sum by (instance) (\n  rate(\n    clickhouse_user_result_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "result: {{instance}}"
      }
     ]
    },
    {
     "title": "Sum User Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user) (\n  rate(\n    clickhouse_user_read_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "read: {{user}}"
      },
      {
       "expr": "sum by (user) (\n  rate(\n    clickhouse_user_written_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "write: {{user}}"
      },
      {
       "expr": "sum by (user) (\n  rate(\n    clickhouse_user_result_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "result: {{user}}"
      }
     ]
    },
    {
     "title": "Sum Table Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (table) (\n  rate(\n    clickhouse_user_read_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "read: {{table}}"
      },
      {
       "expr": "sum by (table) (\n  rate(\n    clickhouse_user_written_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "write: {{table}}"
      },
      {
       "expr": "sum by (table) (\n  rate(\n    clickhouse_user_result_rows{\n      instance=~\"$machine\",\n      user=~\"$username\",\n      table=~\"$tablename\"\n    }[${min_interval}]\n  )\n)",
       "legendFormat": "result: {{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Kind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance, kind) (\n  rate(clickhouse_user_query_num{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{instance}} {{kind}}"
      }
     ]
    },
    {
     "title": "User Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (kind, user) (\n  rate(clickhouse_user_query_num{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{ user }} {{kind}} "
      }
     ]
    },
    {
     "title": "Table Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (kind, table) (\n  rate(clickhouse_user_query_num{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{ table }} {{kind}} "
      }
     ]
    },
    {
     "title": "Node Query Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (kind, instance) (\n  rate(clickhouse_user_memory_usage{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{instance}} {{kind}}"
      }
     ]
    },
    {
     "title": "User Query Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (kind, user) (\n  rate(clickhouse_user_memory_usage{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{ user }} {{kind}}"
      }
     ]
    },
    {
     "title": "Table Query Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (kind, table) (\n  rate(clickhouse_user_memory_usage{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{ table }} {{kind}}"
      }
     ]
    },
    {
     "title": "Node Query Thread Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance, kind) (\n  rate(clickhouse_user_peak_thread_usage{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{instance}} {{kind}}"
      }
     ]
    },
    {
     "title": "User Query Thread Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (kind, user) (\n  rate(clickhouse_user_peak_thread_usage{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{user}} {{ kind }}"
      }
     ]
    },
    {
     "title": "Table Query Thread Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (kind, table) (\n  rate(clickhouse_user_peak_thread_usage{\n    instance=~\"$machine\",\n    user=~\"$username\",\n    table=~\"$tablename\"\n  }[${min_interval}])\n)",
       "legendFormat": "{{table}} {{ kind }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Duration  Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum Query Duration Per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (instance) (\n    rate(\n        clickhouse_user_query_duration_ms{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum Query Duration Per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (user) (\n    rate(\n        clickhouse_user_query_duration_ms{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum  Query Duration Per Table",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (table) (\n    rate(\n        clickhouse_user_query_duration_ms{\n            instance=~\"$machine\",\n            user=~\"$username\",\n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Query Duration Per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (instance) (\n    rate(\n        clickhouse_user_query_duration_ms{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Query Duration Per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (user) (\n    rate(\n        clickhouse_user_query_duration_ms{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Query Duration Per Table",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (table) (\n    rate(\n        clickhouse_user_query_duration_ms{\n            instance=~\"$machine\", \n            user=~\"$username\", \n            table=~\"$tablename\"\n        }[${min_interval}]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merge",
     "type": "timeseries",
     "description": "Number of launched background merges.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_merge[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_merge[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merged rows",
     "type": "timeseries",
     "description": "Rows read for background merges. This is the number of rows before merge.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_merged_rows_total[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_merged_rows_total[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree rows",
     "type": "timeseries",
     "description": "Number of rows INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_merge_tree_data_writer_rows_total[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_merge_tree_data_writer_rows_total[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree uncompressed bytes",
     "type": "timeseries",
     "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_merge_tree_data_writer_uncompressed_bytes_total[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_merge_tree_data_writer_uncompressed_bytes_total[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree compressed bytes",
     "type": "timeseries",
     "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_merge_tree_data_writer_compressed_bytes_total[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_merge_tree_data_writer_compressed_bytes_total[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Reserved space",
     "type": "timeseries",
     "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "clickhouse_disk_space_reserved_for_merge",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read bytes from FD",
     "type": "timeseries",
     "description": "Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_read_buffer_from_file_descriptor_read_bytes_total[2m]))[$__rate_interval:15s] )\n\n\n",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_read_buffer_from_file_descriptor_read_bytes_total[$__rate_interval])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "timeseries",
     "description": "Number of files opened",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_os_open_files[2m]))[$__rate_interval:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_os_open_files[$__rate_interval])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Write bytes to FD",
     "type": "timeseries",
     "description": "Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_write_buffer_from_file_descriptor_write_bytes_total[2m]))[$__rate_interval:15s] )\n\n",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_write_buffer_from_file_descriptor_write_bytes_total[$__rate_interval])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read compressed bytes",
     "type": "timeseries",
     "description": "Number of bytes (the number of bytes before decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_read_compressed_bytes_total[2m]))[$__rate_interval:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_read_compressed_bytes_total[$__rate_interval])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read uncompressed bytes",
     "type": "timeseries",
     "description": "Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_compressed_read_buffer_bytes_total[2m]))[$__rate_interval:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_compressed_read_buffer_bytes_total[$__rate_interval])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Compressed blocks",
     "type": "timeseries",
     "description": "Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_compressed_read_buffer_blocks_total[2m]))[$__rate_interval:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_compressed_read_buffer_blocks_total[$__rate_interval])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inserted rows",
     "type": "timeseries",
     "description": "Number of rows INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_inserted_rows_total[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_inserted_rows_total[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Inserted bytes",
     "type": "timeseries",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_inserted_bytes_total[2m]))[${min_interval}:15s] )",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_inserted_bytes_total[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts",
     "type": "timeseries",
     "description": "Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(clickhouse_delayed_inserts[2m]))[${min_interval}:15s] ) ",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(clickhouse_delayed_inserts[${min_interval}])",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temporary",
     "type": "timeseries",
     "description": "The part is generating now, it is not in data_parts list.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "clickhouse_parts_temporary", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Commited",
     "type": "timeseries",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "clickhouse_parts_committed", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Outdated",
     "type": "timeseries",
     "description": "Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "clickhouse_parts_outdated", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  }
 ]
}